version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      args:
        BACKEND_BASE_IMAGE: "quay.io/centos/centos:stream8"
    volumes:
      - ./server/config.json:/app/server/config.json:ro
      - ./server/logs:/app/logs

  processor:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      args:
        BACKEND_BASE_IMAGE: "quay.io/centos/centos:stream8"
    volumes:
      - ./server/config.json:/app/server/config.json:ro
      - ./server/logs:/app/logs
    entrypoint: npm run start:queue

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      args:
        FRONTEND_BASE_IMAGE: "quay.io/centos/centos:stream8"
    environment:
      APP_PATH: /recurrence
      API_BASE_URL: http://backend:8000
    links:
      - backend:backend
    ports:
      - "8080:80"
