version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      args:
        BASE_IMAGE: "public.ecr.aws/amazonlinux/amazonlinux:2"
    volumes:
      - ./server/.env:/app/server/.env:ro
      - ./server/logs:/app/logs

  processor:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
      args:
        BASE_IMAGE: "public.ecr.aws/amazonlinux/amazonlinux:2"
    volumes:
      - ./server/.env:/app/server/.env:ro
      - ./server/logs:/app/logs
    entrypoint: npm run start:queue-worker

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
      args:
        BASE_IMAGE: "public.ecr.aws/amazonlinux/amazonlinux:2"
    environment:
      APP_PATH: /recurrence
      API_BASE_URL: http://backend:8000
      SERVER_TIMEOUT: 900
    links:
      - backend:backend
    ports:
      - "8080:80"
